const data = {
    products: [
        {
            name: 'OnePlus Bullets Wireless Z2 with Fast Charge',
            slug: 'OnePlus-Bullets-Wireless-Z2-with-Fast-Charge',
            category: 'Electronics',
            image: '/images/p1.jpg',
            price: 1999,
            countInStock: 10,
            brand: 'OnePlus',
            rating: 4.6,
            numReviews: 112,
            description: 'OnePlus Bullets Wireless Z2 with Fast Charge, 30 Hrs Battery Life, Earphones with mic Bluetooth Headset  (Magico Black, In the Ear)',
        },
        {
            name: 'Boult Audio ProBass CurveX with 15hrs Battery Life',
            slug: 'Boult-Audio-ProBass-CurveX-with-15hrs-Battery-Life',
            category: 'Electronics',
            image: '/images/p2.jpg',
            price: 999,
            countInStock: 15,
            brand: 'Boult',
            rating: 4.3,
            numReviews: 108,
            description: 'Boult Audio ProBass CurveX with 15hrs Battery Life, Fastest ever Type-C Charging Bluetooth Headset  (Blue, In the Ear)',
        },
        {
            name: 'boAt Airdopes 161 with 17 Hours Battery and Fast Charge Bluetooth Headset',
            slug: 'boAt-Airdopes-161-with-17-Hours-Battery-and-Fast-Charge-Bluetooth-Headset',
            category: 'Electronics',
            image: '/images/p3.jpg',
            price: 1399,
            countInStock: 15,
            brand: 'boAt',
            rating: 4.1,
            numReviews: 110,
            description: 'boAt Airdopes 161 with 17 Hours Battery and Fast Charge Bluetooth Headset  (Pearl White, True Wireless)',
        },
        {
            name: 'APPLE Watch Series 3 GPS - MTF02HN/A 38 mm Space Grey Aluminium Case with black sprot brand',
            slug: 'APPLE-Watch-Series-3-GPS-MTF02HN/A-38-mm-Space-Grey-Aluminium-Case-with-black-sprot-brand',
            category: 'Electronics',
            image: '/images/p4.jpg',
            price: 20900,
            countInStock: 20,
            brand: 'Apple',
            rating: 4.6,
            numReviews: 125,
            description: 'The Apple Watch Series 3 is a sleek accessory that\'s a must-have if you\'re all about staying fit.',            
        },
    ],
};

export default data;